### ISSUE TITLE
LSTR onnx model converted to tflite model problem

### ISSUE THREAD

**Issue by Hank880223** [PINTO0309/PINTO_model_zoo#175] opened 2022-01-07 12:28 UTC
### Issue Type

Others

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

C++, Python

### Framework

ONNX, TensorFlowLite

### Description

I can successfully convert the pytorch model to the onnx model line through the code you gave, thank you very much,
Then I converted the simplified onnx model to the openvino model, and then from the openvino model to tflite, and encountered some problems. I try to export the tflite model via --weight_replacement_config.
After successfully exporting the tflite model, I tested it but found that the results of the onnx model test were quite different. I guess it may be that my replace json file is written incorrectly, which leads to inconsistent output results. Can you help me find the problem?

onnx mode
[LSTR-onnx.zip](https://github.com/PINTO0309/openvino2tensorflow/files/7828760/LSTR-onnx.zip)

openvino model
[LSTR-openvino.zip](https://github.com/PINTO0309/openvino2tensorflow/files/7828748/LSTR-openvino.zip)

replace json
[lstr-json.zip](https://github.com/PINTO0309/openvino2tensorflow/files/7828764/lstr-json.zip)

test image
[curve.zip](https://github.com/PINTO0309/openvino2tensorflow/files/7828778/curve.zip)

### Relevant Log Output

```shell
onnx output weight log

[[[ 0.32007033  0.4507034   0.04075706 -0.43216056 -0.03198222
    0.31415755  1.2148734  -0.0645135 ]
  [ 0.45342755  0.88767534  0.04075706 -0.43216056 -0.03198222
    0.31415755 -0.6741297  -0.334126  ]
  [ 0.3896584   0.4733551   0.04075706 -0.43216056 -0.03198222
    0.31415755 -1.0076768  -0.26152313]
  [ 0.36454076  0.9713939   0.04075706 -0.43216056 -0.03198222
    0.31415755  0.7288252  -0.02570215]
  [ 0.3855433   0.98734397  0.04075706 -0.43216056 -0.03198222
    0.31415755  0.6614034  -0.03999963]
  [ 0.37322524  0.9657372   0.04075706 -0.43216056 -0.03198222
    0.31415755 -0.6699724  -0.37090972]
  [ 0.43426746  0.9238344   0.04075706 -0.43216056 -0.03198222
    0.31415755 -0.7297871  -0.39202392]]]

tflite output weight log

0.006719 0.001689 0.012175 0.001565 0.003387 0.005521 0.007674 0.008060 
0.003559 0.010446 0.009479 0.009496 0.006681 0.015040 0.002647 0.003966 
0.005076 0.002169 0.004100 0.002876 0.002794 0.004335 0.009175 0.005065 
0.001867 0.004205 0.006904 0.006151 0.006589 0.013605 0.002656 0.003131 
0.005323 0.001880 0.003299 0.002808 0.001679 0.002612 0.012021 0.004772 
0.002001 0.005493 0.004151 0.006104 0.007321 0.008246 0.001275 0.003071 
0.004966 0.002727 0.002599 0.004412 0.001676 0.003357 0.004674 0.002954
```

**Comment by PINTO0309** [comment] 2022-01-08 01:45
I don't understand the value of answering unless you can explain why you don't use the .json committed to this repository.

**Comment by Hank880223** [comment] 2022-01-08 03:11
I tried to submit .json to this repo, but there is no way to convert successfully, the reason is that I converted from onnx model to openvino model and found that the node location inside is slightly different from yours, so I tried to change the .json file to make the model successful convert

After I converted from the pytorch model to the onnx model, I found that the nodes did not have 'Split_988', 'Split_990', so I did not use onnx_optimization.py, I don't know if it will affect the conversion results

![Screenshot from 2022-01-08 11-10-35](https://user-images.githubusercontent.com/84907438/148629594-f96df445-dbee-4215-8e6a-48ab542f6d51.png)

**Comment by PINTO0309** [comment] 2022-01-08 05:12
As for the difference in the shape of the output model, it is possible that your working environment and mine have different versions of the framework. It would be unrealistic for me to deal with the differences in the environments of engineers around the world by myself, so I don't plan to be very proactive.
![Screenshot 2022-01-08 14:02:50](https://user-images.githubusercontent.com/33194443/148632264-de320532-548d-4f6e-8bbf-77b858d8370e.png)

I haven't checked all the structures of the models you attached, but it seems that at least the structure of the final layer is very different.
![Screenshot 2022-01-08 14:05:19](https://user-images.githubusercontent.com/33194443/148632305-d83e7ab6-5c94-4056-97a3-4c6263cd87a2.png)

By the way, I use a Docker container to ensure that the conversion is reproduced correctly. The versions of the various runtimes should always match. Since harmonizing environments is an expensive and non-essential task, it is recommended to try using containers. Since various DeepLearning frameworks such as PyTorch, TensorFlow, and ONNX are all installed, the size of the container is huge at 24GB.
https://github.com/PINTO0309/openvino2tensorflow

**Comment by Hank880223** [comment] 2022-01-08 05:31
Thanks for your answer, I will try to convert the model using the docker container you provided

**Comment by PINTO0309** [comment] 2022-01-20 11:50
Since there seems to be no particular progress, I'll close it.

**Closed by PINTO0309** 2022-01-20 11:50 UTC
