### ISSUE TITLE
gfpgan coreml model

### ISSUE THREAD

**Issue by pravbk100** [PINTO0309/PINTO_model_zoo#385] opened 2024-01-08 11:15 UTC
### Issue Type

Feature Request

### OS

Mac OS

### OS architecture

x86_64, aarch64, Other

### Programming Language

Other

### Framework

PyTorch, CoreML

### Model name and Weights/Checkpoints URL

gfpgan - https://github.com/TencentARC/GFPGAN

### Description

Can you provide the GFPGAN coreml model. The current one which is available on github(john-rocky/CoreML-Models) doesn't work properly. Or can you provide a proper guide to convert from original to coreml.

**Comment by PINTO0309** [comment] 2024-01-08 12:02
Duplicate of https://github.com/PINTO0309/PINTO_model_zoo/issues/262 https://github.com/PINTO0309/PINTO_model_zoo/issues/362

https://github.com/PINTO0309/PINTO_model_zoo/issues?q=gfpgan

**Closed by PINTO0309** 2024-01-08 12:02 UTC
